data/Services.json
Added Azure App Service Environment as private app service option
=> Added Azure App Service Enviroment

data/Services.json
Added Microservices App development details for Amazon as AWS lambda, for GCP as Google cloud Functions and for Oracle as Oracle Functions.
Added App Development/ Deployment (Java /.Net /PHP /Python) for Google as Google App Engine
=> Adding Missing details for Amazon, GCP and Oracle

data/Services.json
Correction of wrong icons.
- Cloud Spanner
- Datastore
=> Correction of wrong icons. (GCP)

data/Services.json
Added Azure Cloud Shell to Cloud Management Tools service
=> Added Azure Cloud Shell

data/Services.json
Amazon Elastic Container Service for Kubernetes
https://aws.amazon.com/eks/
=> adding Amazon EKS

data/Services.json
Updated Azure services, added links, fixed typos
=> Updated Azure

data/Services.json
Added Google Cloud Deployment Manager in *Cloud Deployment Templates/ Infra as Code* service.
=> Added Google Cloud Deployment Manager.

data/Services.json
I added a few modifications to Alibaba Cloud Services.
=> Added few Alibaba Cloud Services.

data/Services.json
Name updated to IBM Container Registry intead of IBM Cloud Kubernetes Services
=> IBM Container Registry name update

data/Services.json
=> Fix Big Query

data/Services.json
Added current AI + Machine Learning services of Azure and removed deprecated ones.
=> Updated Azure Machine Learning

data/Services.json
Reverts ilyas-it83/CloudComparer#100
=> Revert "Updated Azure Machine Learning"

index.html
the page has two report issue button, removing one :D
=> Removed extra issues button

data/Services.json
=> Adding Google Cloud Bare Metal Solution

data/Services.json
Updated several URLs for AWS services
=> Update AWS Service URLs

data/Services.json
added under Developers Tools for Azure Github and Github Codespaces
=> added under Developers Tools for Azure

data/Services.json
=> Update Services.json to correct spelling error

data/Services.json
Signed-off-by: Doug Davis <dug@us.ibm.com>
=> missed one Code Engine entry

data/Services.json
New pull request as the former one was already too messed up.
=> update oci services

data/Services.json
Adding Amazon S3 Glacier Deep Archive under Storage - Long Term Cold Storage
=> Adding Amazon S3 Glacier Deep Archive

data/Services.json
- Updated Cloud services for Oracle cloud
- fixed double category security & Identity, Compliance- Sensitive Data discovery and protection.
=> Updated Cloud services for Oracle cloud and fixed double category 

_data/cloudservices.yml
Add FunctionGraph from Huawei Cloud as Micro Services App Development Platform and Event Driven Computing in the Compute category.
=> cloudservices.yml

_data/cloudservices.yml
Add back FunctionGraph from Huawei products that were deleted by accident in the last merge.
=> Update Huaweicloud products

_data/cloudservices.yml
=> fix and upate some Azure ML services

Gemfile, Gemfile.lock, _data/cloudservices.yml
I have solved issue number 78. 
I have added Azure Databricks into the list and since I ran it in windows I have added the webricks dependencies.
=> Updated Azure Databricks for issue #78

_data/cloudservices.yml
PR to address issue #16 . Added Azure Service Bus to two categories, but didn't call out the individual features (topics and queues) that were specific to each category.
@ilyas-it83 , can you please review?
=> Re-added Azure Service Bus

_data/cloudservices.yml
- Grammatical correction: updated category of "Security & Identity, Compliance" to "Security, Identity & Compliance"
- Changed "Mobile Services: Web/Mobile Authentication Services" to "Security, Identity & Compliance: Customer Identity and Access Management"
- Moved Oracle's "Mobile Hub" offering to the Mobile Services category.
- Added GCP's additional CIAM offering "Identity Platform" to the newly created CIAM category
=> A few updates
